// setup codes generated by command: `npx express-generator api`
let express = require('express');
let router = express.Router();

router.post('/', function(req, res, next) {
  res.send('category');
});

module.exports = router;
