// setup codes generated by command: `npx express-generator api`
let express = require('express');
let router = express.Router();
let app = express();

// cite from: https://www.digitalocean.com/community/tutorials/use-expressjs-to-get-url-and-post-parameters
let bodyParser = require('body-parser');
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));
// citation ends

router.post('/', function(req, res, next) {
  res.send({
    id: 1,
    user_id: 1,
    req: req.body,
    username: req.body.username,
    pet_name: req.body.pet_name,
    avatar: req.body.avatar});
});

module.exports = router;
